In [1]:
import pandas as pd
import numpy as np




In [ ]:
my_data = pd.read_excel('my_data.xlsx')
my_data = np.array(my_data)

my_data

array([[1.2034 , 1.20401, 1.1944 , 1.1965 ],
       [1.1961 , 1.2109 , 1.1946 , 1.2089 ],
       [1.209  , 1.213  , 1.2077 , 1.2123 ],
       ...,
       [1.1618 , 1.16477, 1.16017, 1.1618 ],
       [1.16317, 1.16496, 1.16187, 1.16317],
       [1.16518, 1.16686, 1.16279, 1.16518]], shape=(5685, 4))

In [9]:
def add_column(data, times):
    for i in range(1, times+1):
        new = np.zeros((len(data), 1), dtype=float)
        data = np.append(data, new, axis=1)
        
    return data


def delete_column(data, index, times):
    for i in range(1, times +1):
        data = np.delete(data, index, axis=1)
    return data

In [16]:
my_data_columns_added = add_column(my_data, 5)
my_data_columns_added

array([[1.2034 , 1.20401, 1.1944 , ..., 0.     , 0.     , 0.     ],
       [1.1961 , 1.2109 , 1.1946 , ..., 0.     , 0.     , 0.     ],
       [1.209  , 1.213  , 1.2077 , ..., 0.     , 0.     , 0.     ],
       ...,
       [1.1618 , 1.16477, 1.16017, ..., 0.     , 0.     , 0.     ],
       [1.16317, 1.16496, 1.16187, ..., 0.     , 0.     , 0.     ],
       [1.16518, 1.16686, 1.16279, ..., 0.     , 0.     , 0.     ]],
      shape=(5685, 9))

In [17]:
my_data_columns_deleted = delete_column(my_data_columns_added, 4, 4)
my_data_columns_deleted

array([[1.2034 , 1.20401, 1.1944 , 1.1965 , 0.     ],
       [1.1961 , 1.2109 , 1.1946 , 1.2089 , 0.     ],
       [1.209  , 1.213  , 1.2077 , 1.2123 , 0.     ],
       ...,
       [1.1618 , 1.16477, 1.16017, 1.1618 , 0.     ],
       [1.16317, 1.16496, 1.16187, 1.16317, 0.     ],
       [1.16518, 1.16686, 1.16279, 1.16518, 0.     ]], shape=(5685, 5))

In [18]:
def add_row(data, times):
    for i in range(1, times+1):
        columns = np.shape(data)[1]
        new = np.zeros((1, columns), dtype=float)
        data = np.append(data, new, axis=0)
        return data

def delete_row(data, number):
    data = data[number:, ]
    return data

# An array has the following structure: array[row, column]
# Referring to the whole my_data array
my_data
# Referring to the first 100 rows inside the array
my_data[:100, ]
# Referring to the first 100 rows of the first two columns 
my_data[:100, 0:2]
# Referring to all the rows of the seventh column 
my_data[:, 6]
# Referring to the last 500 rows of the array
my_data[-500:, ]
# Referring to the first row of the first column 
my_data[0, 0]
# Referring to the last row of the last column
my_data[-1, -1]